version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
        - db
    networks:
      - ulrichNetwork
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: ulrich
      MYSQL_PASSWORD: ulrich@
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33066:3306"
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - ulrichNetwork
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8989:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
networks:
  default:
    external:
      name: ulrichNetwork